apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
spec:
  addresses:
  - 172.20.0.120-172.20.0.130
controlplane $ cat l2advert.yml 
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: homelab-l2
spec:
  ipAddressPools:
  - my-pool
